# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Vikram
tagline:          'rand()'
description:     Universität des Saarlandes
url:
baseurl:          /

author:
  name:           'Vikram Narayanan'
  url:

github:
  repo:         arkivm

paginate:         5
gems: [jekyll-paginate]
# Custom vars
version:
